### ISSUE TITLE
Missing LibDBIcon is latest releast as of 10/1/2023

### ISSUE THREAD

**Issue by fireymerlin** [d4kir92/HighLevelAlert#1]
I'm unable to open your discord.  The link provided does not work.  Hopefully you see this.
I'm running an older version

**Comment by d4kir92** [comment]
ingame the link?

**Comment by d4kir92** [comment]
https://discord.gg/cYv2nufppm

**Comment by andrewpong** [comment]
I posted a bug report here: https://discord.com/channels/732803489390133349/1159249805277667348

**Comment by d4kir92** [comment]
done
